#!/bin/bash

declare -a ordering
declare -A cmds

dmopts="$@"

item () {
	cmdType=`type -t $2`
	ordering+=("$1")
	if [ "$cmdType" = "function" ]; then
		cmds[$1]="$2"
	else
		cmds[$1]="exec $2"
	fi
}

. "$HOME/.dmenu_quicklist"

output_list () {
	for v in "${ordering[@]}" ; do
		echo $v
	done
}

run_cmd_for_selection () {
	c="$1"
	shift
	${cmds[$c]} "$@"
}

selected=`output_list | dmenu "$@"`
#echo "   $selected"
run_cmd_for_selection $selected

